--- #YAML:1.0
name:               Classic-Perl
version:            0.04
abstract:           Selectively reinstate deleted Perl features
author:
    - Father Chrysostomos <sprout at, er, cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    XSLoader:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Classic-Perl
    license:     http://dev.perl.org/licenses/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
